### ISSUE TITLE
Error: rex_yrewrite ist nicht installiert führt zur Exception

### ISSUE THREAD

**Issue by joachimdoerr** [alexplusde/be_style_fluent#1]
Error thrown with message "Class 'rex_yrewrite' not found"

Stacktrace:
#6 Error in //redaxo/src/addons/be_style_fluent/fragments/core/navigations/meta.php:39
#5 require in //redaxo/src/core/lib/fragment.php:111
#4 rex_fragment:parse in //redaxo/src/core/layout/top.php:220
#3 require in /redaxo/src/core/lib/be/controller.php:411
#2 rex_be_controller:includeCurrentPage in //redaxo/src/core/backend.php:226
#1 require in //redaxo/src/core/boot.php:137
#0 require in //redaxo/index.php:9

**Comment by alexplusde** [comment]
Muss in package.yml notiert werden.

**Comment by alxndr-w** [comment]
im installer in 3.0.2 gefixt

**Comment by eaCe** [comment]
Hm, ich habe es eben mal installiert, es fliegt mir um die Ohren, auch mit yrewrite. Komisch
![grafik](https://user-images.githubusercontent.com/2708231/232225028-1af0eb42-53b0-4a54-932d-bd2b21bce98b.png)

**Comment by alxndr-w** [comment]
Man könnte es optional machen, aber da in der Community jeder seine eigenen Styles-Addons macht, sah ich da keinen akuten Bedarf.
