### ISSUE TITLE
Code Hieroglyphen

### ISSUE THREAD

**Issue by HassChristian** [alexplusde/be_style_fluent#10]
Hey Alex, wenn ich deinen frischen Style aktiviere, wird mir ein komischer Code am Ende der Seite angehängt. 

![Screenshot 2022-01-10](https://user-images.githubusercontent.com/26849978/148768449-15146c80-ed57-4746-a401-33f6ba848a7d.png)
 
Ist mir heute aufgefallen. Ab Redaxo 5.13.1

**Comment by alxndr-w** [comment]
Sicher, dass der nicht auch ohne da ist, du ihn aber nicht siehst? Kannst du das Addon deaktivieren und in den Quellcode / DOM des Browsers nachsehen?

**Comment by HassChristian** [comment]
Es ist nur bei aktivierten Addon. Ich sehe es auch nur im Firefox. Hab keine Ahnung warum... Hab das XCORE Addon heute abgeklemmt. Als ich fertig war hab ich es im Browser gesehen.
Der Code ist hinten ans html angehängt. Gehe mal im Firefox auf christianhass.net, da sollte es sichtbar sein...

**Comment by alxndr-w** [comment]
@HassChristian könntest du dennoch einmal so vorgehen, wie oben beschrieben?

**Comment by HassChristian** [comment]
Okay. Gemacht! Kann den Fehler nicht mehr reproduzieren. Ich weiß nicht was es war. 

Hatte XCORE vorher deaktiviert und musste ein paar Änderungen vornehmen, Ich kann mir nicht vorstellen, dass es daran gelegen hat.

Sorry, danke für deine Zeit!

**Comment by alxndr-w** [comment]
Kein Problem. Passiert mir auch, man vermutet es dort, wo man es zunächst beobachtet hat.
