### ISSUE TITLE
Branding Label overflow

### ISSUE THREAD

**Issue by eaCe** [alexplusde/be_style_fluent#18]
![grafik](https://user-images.githubusercontent.com/2708231/232247397-1e8e20be-9850-4128-8708-0e6501e46642.png)

**Comment by alxndr-w** [comment]
Habe ich nicht. Ist das ein bestimmter Breakpoint?

**Comment by eaCe** [comment]
Das habe ich z.B. bei 1920px Breite.
Die dt Elemente haben eine feste Breite. Und die Columns sind `col-md-4`.
Wenn ich diese  auf `col-md-4 col-lg-6` setze past alles. 
Wenn du möchtest übernehme ich das in meinem PR.

**Comment by alxndr-w** [comment]
Das wundert mich, weil es bei mir wie gesagt richtig aussieht auf der Breite.
