### ISSUE TITLE
Schatten in Quick Navigation überlappen

### ISSUE THREAD

**Issue by omphteliba** [alexplusde/be_style_fluent#3]
Ich spiel grad mit dem Fluent Addon rum, und sehe dass die Button-Leiste vom Quick-Navigation Addon "komische" Schatten hat:

![image](https://user-images.githubusercontent.com/196336/133241012-458fe8e2-6bfe-4d7a-8343-afcdd4a7c23c.png)

Das sieht sonst eher so aus:

![image](https://user-images.githubusercontent.com/196336/133240831-256275a3-4df7-475d-a110-c206125b1ab1.png)

Ich weiss nicht ob das im Fluent Design so aussehen soll, oder ob dich das überhaupt interessiert, weil es ja ein anderes Addon betrifft.

**Comment by alxndr-w** [comment]
ja, da müsste man Ausnahmen im CSS für machen. PR welcome

**Comment by alxndr-w** [comment]
in 3.0.2
