### ISSUE TITLE
Menü "Neu" sollte nur das anzeigen, was auch wirklich nutzbar/installiert ist

### ISSUE THREAD

**Issue by iceman-fx** [alexplusde/be_style_fluent#5]
Im Menü Neu werden Einträge angezeigt, welche ohne Funktion sind, da das entsprechende Addon nicht verfügbar ist.
Z.B. Globale Einstellung oder Cronjob

Hier wäre es sinnvoll, wenn vorher geprüft wird, ob das entsprechende Addon auch installiert/aktiviert ist.

**Comment by alxndr-w** [comment]
Absolut. Der Teil dazu befindet sich im Fragment-Ordner, wäre das für dich machbar anzupassen?

**Comment by alxndr-w** [comment]
Einen PR dazu würde ich nach wie vor entgegen nehmen.

**Comment by eaCe** [comment]
Ich bau dir einen
