### ISSUE TITLE
Kompatibilität zu be_tools-Addon

### ISSUE THREAD

**Issue by ritzfritz** [alexplusde/be_style_fluent#6]
```
    display: block;
    width: 400px;
    overflow-y: auto;
```

**Comment by alxndr-w** [comment]
ich muss mir hier leider nochmal genauer anschauen, in welche Klasse ich das css packen muss.

**Comment by eaCe** [comment]
Geht es da um die Sidebar? Die Breite würde ich nicht verändern. Das kann man selbst machen, wenn man das braucht. Für die Styles hier ein Vorschlag, auch damit es ins Gesamtbild passt

![grafik](https://user-images.githubusercontent.com/2708231/232273001-d2ab228f-6d14-4e59-944b-ab96ba6d6bcd.png)

**Comment by alxndr-w** [comment]
Nehme ich auch gerne an, ich nutze be_tools nicht

**Comment by eaCe** [comment]
Ich auch nicht, habe es nur mal installiert. Ich dachte wenn ich schon dran arbeite kann ich mir das mal ansehen.
